version: "3.8"

services:
  app.postgres.db:
    image: "postgres:12.2"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data

  app.web:
    build: .
    command: bash start.sh
    ports:
      - "3000:3000"
    environment:
      - DB_PASSWORD=postgres
    volumes:
      - .:/exchange
      - gems:/gems
    depends_on:
      - app.postgres.db

volumes:
  postgres:
  gems:
