version: "3.8"

services:
  app.postgres.db:
    image: "postgres:12.2"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data

  app.web:
    build: ./api
    command: bash start.sh
    ports:
      - "3001:3000"
    environment:
      - DB_PASSWORD=postgres
    volumes:
      - .:/exchange
      - gems:/gems
    depends_on:
      - app.postgres.db

  app.front:
    build: ./web
    command: yarn start
    ports:
      - '3000:3000'
    volumes:
      - ./web:/web
    depends_on:
      - app.web

volumes:
  postgres:
  gems:
