version: '3'
services:
  app.postgres.db:
    image: postgres
    volume:
      - ./tmp/db:/var/lib/postgresql/data
  app.web:
    build: .
    command: bash start.sh
    volumes:
      - .:/ToDo
      - gems:/gems
    ports:
      - "3000:3000"
    depends_on: 
      - app.postgres.db