version: '3'
services:
  app.postgres.db:
    image: postgres
    restart: always
    environment: 
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - 5432
  app.web:
    build: .
    command: bash start.sh
    volumes:
      - .:/ToDo
      - gems:/gems
    ports:
      - "3000:3000"
    depends_on: 
      - app.postgres.db
volumes:
  postgres:
  gems:
