default: &default
  adapter: postgresql
  encoding: unicode
  host: app.postgres.db
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ToDo_development
test:
  <<: *default
  database: ToDo_test
production:
  <<: *default
  database: ToDo_production
