default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: app.postgres.db
  user: postgres
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: ToDo_development
test:
  <<: *default
  database: ToDo_test
production:
  <<: *default
  database: ToDo_production
